### ISSUE TITLE
Exporting as Image with overlaping shifts results in the second shift being blank

### ISSUE THREAD

**Issue by Bernardo-Pinto** [joaocmd/Criador-Horarios#14]
![ist-horario(1)](https://user-images.githubusercontent.com/50909054/108634321-02adc080-7471-11eb-8b11-1c39ef67c16a.png)
![ist-horario(2)](https://user-images.githubusercontent.com/50909054/108634362-253fd980-7471-11eb-882a-d26a14ad833c.png)

**Comment by masterzeus05** [comment]
This PR should correct that as we are now using a new way of exporting the schedule to an image. Thank you for your feedback!
