### ISSUE TITLE
Shared URL calendar doesn't match original

### ISSUE THREAD

**Issue by andre15silva** [joaocmd/Criador-Horarios#25]
URL: https://horarios.dagoncalves.me/?s=283085589463407~L02~T01;283085589463268~L03~T01;283085589463237~TP03&d=MEIC-A

Original calendar:

![pic-selected-210907-1821-38](https://user-images.githubusercontent.com/31904862/132385748-e8f11aef-f346-4c17-a7e6-eafd4c475efe.png)

Restored calendar:

![pic-selected-210907-1822-29](https://user-images.githubusercontent.com/31904862/132385835-768dee88-3963-4adf-850c-9c7245fa5bb0.png)

At a first glance, the collision seems to be because of both conflicting shifts being called `TP03` but in different campi

**Comment by masterzeus05** [comment]
Hey @andre15silva!
This is a problem that we have already noted, there was a change in the shifts and we have not yet looked at how they are supposed to work, we will look into it!

**Comment by masterzeus05** [comment]
@andre15silva this should be fixed by now! if it isn't warn us please!

**Comment by andre15silva** [comment]
It does work, thanks!
